import { Panchayat, ModelHealth } from "./types";

export const PANCHAYATS_DATA: Panchayat[] = [
  {
    lgd_code: "MH_PUN_001",
    panchayat_name: "Wagholi Gram Panchayat",
    village_name: "Wagholi",
    taluka: "Haveli",
    district: "Pune",
    state: "Maharashtra",
    zone: "Maharashtra",
    latitude: 18.5793,
    longitude: 73.9814,
    elevation_m: 570,
    slope_deg: 3.2,
    aspect_deg: 140,
    cropland_frac: 0.45,
    forest_frac: 0.05,
    builtup_frac: 0.40,
    soil_clay_pct: 38.0,
    soil_type: "Black Cotton Soil (Vertisol)",
    latest_rainfall_estimate: 2.4,
    latest_baseline_rainfall: 4.8,
    latest_temp_estimate: 28.5,
    latest_rain_prob: 0.35,
    latest_range: [0.0, 5.2],
    trust_label: "High",
    trust_score: 0.86,
    trust_reason: "High Trust: Model demonstrated +64.3% error reduction over raw NWP in Maharashtra."
  },
  {
    lgd_code: "MH_PUN_002",
    panchayat_name: "Malegaon Budruk Gram Panchayat",
    village_name: "Malegaon Bk",
    taluka: "Baramati",
    district: "Pune",
    state: "Maharashtra",
    zone: "Maharashtra",
    latitude: 18.1512,
    longitude: 74.5775,
    elevation_m: 548,
    slope_deg: 1.8,
    aspect_deg: 90,
    cropland_frac: 0.78,
    forest_frac: 0.02,
    builtup_frac: 0.12,
    soil_clay_pct: 45.0,
    soil_type: "Deep Black Clay Soil",
    latest_rainfall_estimate: 1.2,
    latest_baseline_rainfall: 3.5,
    latest_temp_estimate: 30.2,
    latest_rain_prob: 0.20,
    latest_range: [0.0, 3.8],
    trust_label: "High",
    trust_score: 0.84,
    trust_reason: "High Trust: Strong rainshadow false alarm suppression validated."
  },
  {
    lgd_code: "MH_PUN_003",
    panchayat_name: "Otur Gram Panchayat",
    village_name: "Otur",
    taluka: "Junnar",
    district: "Pune",
    state: "Maharashtra",
    zone: "Maharashtra",
    latitude: 19.2611,
    longitude: 73.9868,
    elevation_m: 680,
    slope_deg: 6.5,
    aspect_deg: 230,
    cropland_frac: 0.62,
    forest_frac: 0.22,
    builtup_frac: 0.08,
    soil_clay_pct: 32.0,
    soil_type: "Reddish Loamy Forest Soil",
    latest_rainfall_estimate: 4.8,
    latest_baseline_rainfall: 7.2,
    latest_temp_estimate: 26.8,
    latest_rain_prob: 0.62,
    latest_range: [1.5, 8.4],
    trust_label: "High",
    trust_score: 0.81,
    trust_reason: "High Trust: Terrain lapse-rate and slope curvature bias corrected."
  },
  {
    lgd_code: "MH_SAT_001",
    panchayat_name: "Tapola Gram Panchayat",
    village_name: "Tapola",
    taluka: "Mahabaleshwar",
    district: "Satara",
    state: "Maharashtra",
    zone: "Maharashtra",
    latitude: 17.7833,
    longitude: 73.6833,
    elevation_m: 890,
    slope_deg: 14.2,
    aspect_deg: 270,
    cropland_frac: 0.30,
    forest_frac: 0.55,
    builtup_frac: 0.04,
    soil_clay_pct: 28.0,
    soil_type: "Laterite Mountain Soil",
    latest_rainfall_estimate: 12.5,
    latest_baseline_rainfall: 6.8,
    latest_temp_estimate: 23.4,
    latest_rain_prob: 0.88,
    latest_range: [6.0, 18.5],
    trust_label: "High",
    trust_score: 0.89,
    trust_reason: "High Trust: High-altitude Western Ghats orographic uplift capture."
  },
  {
    lgd_code: "MH_SOL_001",
    panchayat_name: "Kasegaon Gram Panchayat",
    village_name: "Kasegaon",
    taluka: "Pandharpur",
    district: "Solapur",
    state: "Maharashtra",
    zone: "Maharashtra",
    latitude: 17.6744,
    longitude: 75.3242,
    elevation_m: 462,
    slope_deg: 1.2,
    aspect_deg: 110,
    cropland_frac: 0.82,
    forest_frac: 0.01,
    builtup_frac: 0.10,
    soil_clay_pct: 52.0,
    soil_type: "Heavy Black Vertisol",
    latest_rainfall_estimate: 0.8,
    latest_baseline_rainfall: 2.6,
    latest_temp_estimate: 31.8,
    latest_rain_prob: 0.15,
    latest_range: [0.0, 2.5],
    trust_label: "High",
    trust_score: 0.82,
    trust_reason: "High Trust: Arid rain-shadow zone validated with station archive."
  },
  {
    lgd_code: "KA_BEL_001",
    panchayat_name: "Nipani Gram Panchayat",
    village_name: "Nipani Rural",
    taluka: "Chikkodi",
    district: "Belagavi",
    state: "Karnataka",
    zone: "Karnataka",
    latitude: 16.3980,
    longitude: 74.3820,
    elevation_m: 625,
    slope_deg: 3.8,
    aspect_deg: 180,
    cropland_frac: 0.72,
    forest_frac: 0.10,
    builtup_frac: 0.12,
    soil_clay_pct: 40.0,
    soil_type: "Medium Black and Red Loam",
    latest_rainfall_estimate: 3.2,
    latest_baseline_rainfall: 5.1,
    latest_temp_estimate: 27.9,
    latest_rain_prob: 0.45,
    latest_range: [0.5, 6.2],
    trust_label: "High",
    trust_score: 0.85,
    trust_reason: "High Trust: Model demonstrated +64.9% error reduction in Karnataka."
  },
  {
    lgd_code: "KA_DHA_001",
    panchayat_name: "Gokul Gram Panchayat",
    village_name: "Gokul",
    taluka: "Hubballi",
    district: "Dharwad",
    state: "Karnataka",
    zone: "Karnataka",
    latitude: 15.3647,
    longitude: 75.0833,
    elevation_m: 665,
    slope_deg: 2.5,
    aspect_deg: 200,
    cropland_frac: 0.68,
    forest_frac: 0.08,
    builtup_frac: 0.18,
    soil_clay_pct: 42.0,
    soil_type: "Black Cotton Soil",
    latest_rainfall_estimate: 2.1,
    latest_baseline_rainfall: 4.4,
    latest_temp_estimate: 28.6,
    latest_rain_prob: 0.32,
    latest_range: [0.0, 4.8],
    trust_label: "High",
    trust_score: 0.83,
    trust_reason: "High Trust: Strong diurnal temperature and moisture agreement."
  },
  {
    lgd_code: "KA_BAG_001",
    panchayat_name: "Savalagi Gram Panchayat",
    village_name: "Savalagi",
    taluka: "Jamkhandi",
    district: "Bagalkot",
    state: "Karnataka",
    zone: "Karnataka",
    latitude: 16.5122,
    longitude: 75.3211,
    elevation_m: 530,
    slope_deg: 1.5,
    aspect_deg: 80,
    cropland_frac: 0.80,
    forest_frac: 0.02,
    builtup_frac: 0.12,
    soil_clay_pct: 48.0,
    soil_type: "Deep Black Clayey",
    latest_rainfall_estimate: 1.5,
    latest_baseline_rainfall: 3.8,
    latest_temp_estimate: 30.5,
    latest_rain_prob: 0.22,
    latest_range: [0.0, 3.5],
    trust_label: "High",
    trust_score: 0.80,
    trust_reason: "High Trust: Northern dry zone calibration active."
  },
  {
    lgd_code: "KA_HAS_001",
    panchayat_name: "Hettur Gram Panchayat",
    village_name: "Hettur",
    taluka: "Sakleshpur",
    district: "Hassan",
    state: "Karnataka",
    zone: "Karnataka",
    latitude: 12.8333,
    longitude: 75.8000,
    elevation_m: 950,
    slope_deg: 12.5,
    aspect_deg: 250,
    cropland_frac: 0.40,
    forest_frac: 0.50,
    builtup_frac: 0.05,
    soil_clay_pct: 25.0,
    soil_type: "Humus-rich Lateritic Soil",
    latest_rainfall_estimate: 14.8,
    latest_baseline_rainfall: 7.9,
    latest_temp_estimate: 22.8,
    latest_rain_prob: 0.92,
    latest_range: [8.5, 21.0],
    trust_label: "High",
    trust_score: 0.88,
    trust_reason: "High Trust: Western Ghats high-rainfall plantation zone resolved."
  },
  {
    lgd_code: "TS_MED_001",
    panchayat_name: "Haveli Ghanpur Gram Panchayat",
    village_name: "Haveli Ghanpur",
    taluka: "Medak Rural",
    district: "Medak",
    state: "Telangana",
    zone: "Telangana",
    latitude: 18.0489,
    longitude: 78.2612,
    elevation_m: 485,
    slope_deg: 2.1,
    aspect_deg: 120,
    cropland_frac: 0.65,
    forest_frac: 0.12,
    builtup_frac: 0.15,
    soil_clay_pct: 28.0,
    soil_type: "Red Sandy Loam (Chalka)",
    latest_rainfall_estimate: 2.8,
    latest_baseline_rainfall: 4.6,
    latest_temp_estimate: 30.8,
    latest_rain_prob: 0.40,
    latest_range: [0.2, 5.8],
    trust_label: "High",
    trust_score: 0.81,
    trust_reason: "High Trust: Model demonstrated +57.4% error reduction in Telangana."
  },
  {
    lgd_code: "TS_SID_001",
    panchayat_name: "Pregnapur Gram Panchayat",
    village_name: "Pregnapur",
    taluka: "Gajwel",
    district: "Siddipet",
    state: "Telangana",
    zone: "Telangana",
    latitude: 17.8465,
    longitude: 78.6833,
    elevation_m: 512,
    slope_deg: 1.9,
    aspect_deg: 105,
    cropland_frac: 0.70,
    forest_frac: 0.08,
    builtup_frac: 0.16,
    soil_clay_pct: 32.0,
    soil_type: "Red Sandy Loam / Mixed",
    latest_rainfall_estimate: 3.5,
    latest_baseline_rainfall: 5.2,
    latest_temp_estimate: 30.1,
    latest_rain_prob: 0.48,
    latest_range: [0.5, 6.8],
    trust_label: "High",
    trust_score: 0.79,
    trust_reason: "High Trust: Semi-arid plateau microclimate validated."
  },
  {
    lgd_code: "TS_WAR_001",
    panchayat_name: "Rayaparthy Gram Panchayat",
    village_name: "Rayaparthy",
    taluka: "Wardhannapet",
    district: "Warangal",
    state: "Telangana",
    zone: "Telangana",
    latitude: 17.8012,
    longitude: 79.6234,
    elevation_m: 275,
    slope_deg: 1.4,
    aspect_deg: 95,
    cropland_frac: 0.75,
    forest_frac: 0.06,
    builtup_frac: 0.14,
    soil_clay_pct: 35.0,
    soil_type: "Red Earth / Black Alluvial Mix",
    latest_rainfall_estimate: 4.1,
    latest_baseline_rainfall: 6.0,
    latest_temp_estimate: 31.4,
    latest_rain_prob: 0.54,
    latest_range: [1.0, 7.5],
    trust_label: "High",
    trust_score: 0.82,
    trust_reason: "High Trust: Godavari basin rain distribution adjusted."
  },
  {
    lgd_code: "TS_MAH_001",
    panchayat_name: "Badepalle Gram Panchayat",
    village_name: "Badepalle",
    taluka: "Jadcherla",
    district: "Mahabubnagar",
    state: "Telangana",
    zone: "Telangana",
    latitude: 16.7667,
    longitude: 78.1333,
    elevation_m: 508,
    slope_deg: 2.3,
    aspect_deg: 150,
    cropland_frac: 0.72,
    forest_frac: 0.05,
    builtup_frac: 0.18,
    soil_clay_pct: 26.0,
    soil_type: "Red Sandy Loam (Dubba)",
    latest_rainfall_estimate: 1.8,
    latest_baseline_rainfall: 3.9,
    latest_temp_estimate: 32.2,
    latest_rain_prob: 0.28,
    latest_range: [0.0, 4.2],
    trust_label: "High",
    trust_score: 0.80,
    trust_reason: "High Trust: Southern dry zone temperature and rain balance calibrated."
  }
];

export const MODEL_HEALTH_DATA: ModelHealth = {
  model_version: "meghdrishti_v1",
  last_trained: "2026-10-03",
  training_records: 33605,
  validation_records: 11895,
  test_records: 13780,
  panchayat_count: 13,
  model_type: "LightGBM GBDT + Residual Quantile Calibrator",
  data_coverage: "99.8%",
  data_quality: "High (0 missing values, 0 impossible coordinates)",
  historical_skill: "+62.5% Error Reduction vs Coarse NWP",
  station_density: "13 Calibrated Panchayat Hubs across 3 Agro-Climatic Zones",
  status: "Healthy",
  system_operational: true
};
